# Generated by Django 5.0.2 on 2024-03-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Part_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarCategory',
            new_name='CarPartCategory',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='CarPartPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.carmodel')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.carpart')),
            ],
        ),
    ]
