# Generated by Django 5.0.2 on 2024-03-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Part_App', '0002_rename_carcategory_carpartcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.carmodel')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.carpart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_Part_App.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='CarPartPurchase',
        ),
    ]
